import test from 'node:test';
import assert from 'node:assert/strict';
import {BOARDS} from '../public/data.js';
import {createGame,next,selectSeat,selectable,choose,canNext,nightSteps,inspection,previous,upgradeGame,restartGame,roleName,gunSources,hasLastWords,subtitle} from '../public/engine.js';
import {trueWinner,basicActor,ordinaryWolves,settleNight} from '../public/night.js';
import {transformCandidates,realWolf,nativeAllowed,graveResult} from '../public/identity.js';
import {recapNights} from '../public/records.js';
import {cardModel} from '../public/recap.js';
const go=s=>assert.equal(next(s),true,s.step);
function ready(board='gargoyle12'){const s=createGame(board,{sheriff:false});let id=1;for(const[r,n]of Object.entries(BOARDS[board].roles))for(let i=0;i<n;i++)s.players[id++-1].role=r;s.rolesConfirmed=true;s.deathsCommitted=true;return s;}
const seat=(s,r)=>s.players.find(p=>p.role===r).id;
function transform(s,id){s.step='transform';assert.equal(next(s),false);assert.equal(choose(s,'skip'),false);assert.equal(selectSeat(s,id),true);go(s);}
function exile(s,id){s.step='exileVote';s.votePool=s.players.filter(p=>p.alive).map(p=>p.id);selectSeat(s,id);go(s);}
for(const board of ['gargoyle10','gargoyle12']){
 test(board+' first-night public registration and full fixed order',()=>{
  const s=createGame(board,{sheriff:false}),assigned={};let id=1;for(const[r,n]of Object.entries(BOARDS[board].roles))assigned[r]=Array.from({length:n},()=>id++);
  go(s);let changed=false;for(let i=0;i<50&&s.step!=='dawn';i++){
   if(!s.rolesConfirmed&&['wolves','guard','witch','seer','gravekeeper','hunter'].includes(s.step))for(const id of s.step==='wolves'?[...assigned.gargoyle,...assigned.wolf]:assigned[s.step])selectSeat(s,id);
   if(s.step==='guardTarget')choose(s,'skip');if(s.step==='attack')choose(s,'skip');if(s.step==='transform'){selectSeat(s,assigned.villager.at(-1));changed=true;}
   if(s.step==='antidote'&&!canNext(s))choose(s,'skip');if(s.step==='poison'&&!canNext(s))choose(s,'skip');if(s.step==='inspect')selectSeat(s,assigned.gargoyle[0]);go(s);
  }
  assert.equal(s.step,'dawn');assert.ok(changed);assert.equal(s.players.filter(p=>p.role==='villager').length,4);
  assert.equal(recapNights(s)[0].events.filter(e=>e.skill==='transform').length,1);
  assert.equal(nightSteps(s).includes('graveResult'),false);s.night=2;assert.equal(nightSteps(s).includes('transform'),false);assert.equal(nightSteps(s).includes('converted'),false);
  assert.equal(nightSteps(s).includes('hunter'),board==='gargoyle12');
 });
 test(board+' wrap adjacency includes last seat and cannot transform original wolf',()=>{const s=ready(board);assert.ok(transformCandidates(s).includes(BOARDS[board].playerCount));s.step='transform';assert.equal(selectSeat(s,1),false);assert.equal(selectSeat(s,2),false);});
 test(board+' converted knife target remains wolf and conversion survives self-knife',()=>{const s=ready(board),id=BOARDS[board].playerCount;s.nightAction.attack=id;transform(s,id);assert.ok(realWolf(s,s.players[id-1]));s.step='antidote';choose(s,'skip');go(s);assert.ok(s.nightState.deaths.some(d=>d.id===id));assert.equal(s.gargoyle.target,id);assert.equal(nightSteps(s).includes('converted'),false);
  const x=ready(board);x.nightAction.attack=1;transform(x,id);x.step='antidote';choose(x,'skip');go(x);assert.equal(x.gargoyle.target,id);assert.equal(x.winner,null);
 });
 test(board+' takeover waits until next night and disables guard before guard page',()=>{const s=ready(board),id=seat(s,'guard');transform(s,id);assert.equal(basicActor(s).id,1);s.players.filter(p=>p.role==='wolf').forEach(p=>p.alive=false);exile(s,1);assert.equal(s.winner,null);assert.equal(s.gargoyle.joinNight,2);assert.equal(nativeAllowed(s,s.players[id-1]),true);s.step='nextNight';go(s);assert.equal(nativeAllowed(s,s.players[id-1]),false);assert.equal(basicActor(s).id,id);s.step='guardTarget';assert.equal(selectSeat(s,id),false);assert.equal(choose(s,'skip'),false);assert.equal(canNext(s),true);s.step='attack';selectSeat(s,id);assert.equal(settleNight(s).events.length,1);
 });
 test(board+' transformation snapshot, rollback, refresh and restart',()=>{const s=ready(board);s.step='transform';selectSeat(s,BOARDS[board].playerCount);go(s);const loaded=upgradeGame(JSON.parse(JSON.stringify(s)));assert.deepEqual(loaded,s);previous(loaded);assert.equal(loaded.gargoyle.target,null);assert.equal(loaded.step,'transform');go(loaded);assert.ok(loaded.gargoyle.target);const fresh=restartGame(loaded);assert.equal(fresh.gargoyle.target,null);assert.deepEqual(fresh.exiles,[]);assert.deepEqual(fresh.rules,loaded.rules);});
}
test('seer reply is separate from actual camp on first night, changes on second',()=>{const s=ready();transform(s,12);s.nightAction.inspect=12;assert.equal(inspection(s),'up');s.night=2;assert.equal(inspection(s),'down');s.nightAction.inspect=1;assert.equal(inspection(s),'down');});
test('converted citizen immediately leaves good citizen victory count',()=>{const s=ready();transform(s,12);s.players.filter(p=>p.role==='villager'&&p.id!==12).forEach(p=>p.alive=false);assert.equal(trueWinner(s),'狼人陣營');s.rules.victory='city';assert.equal(trueWinner(s),null);s.players.filter(p=>!realWolf(s,p)).forEach(p=>p.alive=false);assert.equal(trueWinner(s),'狼人陣營');});
test('converted god immediately leaves good god count; not added to basic wolves yet',()=>{const s=ready();transform(s,4);s.players.filter(p=>p.role!=='villager'&&!realWolf(s,p)).forEach(p=>p.alive=false);assert.equal(trueWinner(s),'狼人陣營');assert.equal(ordinaryWolves(s).some(p=>p.id===4),false);});
test('last original wolf poisoned after knife cannot add another knife this night',()=>{const s=ready();transform(s,12);s.players.filter(p=>p.role==='wolf').forEach(p=>p.alive=false);s.nightAction.attack=9;s.step='antidote';choose(s,'skip');go(s);s.step='poison';choose(s,'use');selectSeat(s,1);go(s);assert.equal(s.winner,null);assert.equal(settleNight(s).events.filter(e=>e.cause==='attack').length,1);assert.equal(s.gargoyle.joinNight,null);s.deathsCommitted=false;s.step='announcement';go(s);assert.equal(s.gargoyle.joinNight,2);});
test('gravekeeper reads only real formal exile camp snapshot and executes one recap card',()=>{const s=ready();transform(s,12);exile(s,12);assert.ok(s.exiles[0].wolf);s.step='nextNight';go(s);assert.equal(graveResult(s).id,12);assert.ok(nightSteps(s).includes('graveResult'));s.step='graveResult';go(s);const e=recapNights(s).at(-1).events.find(e=>e.skill==='gravekeeper');assert.equal(e.result,'狼人');const c=cardModel(e);assert.equal(c.tone,'god');assert.equal(c.image,'art/catalog/gravekeeper.png');});
test('gravekeeper skips result on explosion/no exile; native skill blocked after takeover',()=>{const s=ready();s.night=2;assert.equal(graveResult(s),null);assert.equal(nightSteps(s).includes('graveResult'),false);s.gargoyle={...s.gargoyle,target:seat(s,'gravekeeper'),joinNight:2};s.exiles=[{day:1,id:2,wolf:true}];assert.equal(nightSteps(s).includes('graveResult'),false);});
test('converted hunter gun retained before takeover, suppressed after and poison',()=>{const s=ready();s.gargoyle.target=seat(s,'hunter');const d={id:s.gargoyle.target,cause:'exile',context:'day'};assert.deepEqual(gunSources(s,d),['native']);assert.deepEqual(gunSources(s,{...d,cause:'poison'}),[]);s.gargoyle.joinNight=2;s.night=2;assert.deepEqual(gunSources(s,d),[]);});
test('converted knife recap stays original portrait and red name',()=>{const s=ready();transform(s,4);s.players.filter(p=>['wolf','gargoyle'].includes(p.role)).forEach(p=>p.alive=false);s.step='nextNight';go(s);s.step='attack';selectSeat(s,12);go(s);s.step='antidote';choose(s,'skip');go(s);const e=recapNights(s).at(-1).events.find(e=>e.skill==='wolf-attack');assert.deepEqual(e.actors,[4]);assert.equal(cardModel(e).tone,'wolf');assert.equal(cardModel(e).name,'轉化者（守）');assert.equal(roleName(s,s.players[3]),'轉化者（守）');});
for(const day of [1,2,5])for(const origin of ['exile','attack'])test('hunter shot last words day '+day+' '+origin,()=>{const s=ready('12');s.night=day;const d={id:12,cause:'shot',day,sourceRole:'hunter',skillSource:'native',shooterCause:origin,shooterContext:origin==='exile'?'day':'night'};assert.equal(hasLastWords(s,d),origin==='exile');assert.equal(hasLastWords(s,{...d,sourceRole:'king'}),day===1);});
test('blood fixed two-page captions and mandatory target',()=>{const s=ready('blood12');s.players.filter(p=>p.role==='wolf').forEach(p=>p.alive=false);exile(s,1);assert.equal(subtitle(s),'1號玩家出局');go(s);assert.equal(subtitle(s),'血月使者請選擇你要襲擊的對象');assert.equal(next(s),false);assert.equal(choose(s,'skip'),false);});
for(const role of ['seer','witch','guard','gravekeeper','hunter','villager'])test('converted '+role+' native skill and original portrait survive until takeover',()=>{const s=ready(),target=4,existing=seat(s,role),old=s.players[target-1].role;s.players[target-1].role=role;s.players[existing-1].role=old;transform(s,target);assert.ok(realWolf(s,s.players[target-1]));assert.ok(nativeAllowed(s,s.players[target-1]));assert.equal(s.gargoyle.originalRole,role);s.players.filter(p=>['gargoyle','wolf'].includes(p.role)).forEach(p=>p.alive=false);s.step='nextNight';go(s);assert.equal(s.gargoyle.joinNight,2);assert.equal(nativeAllowed(s,s.players[target-1]),false);assert.equal(basicActor(s).id,target);assert.equal(s.players[target-1].role,role);});
test('conversion of last good citizen immediately terminates further stages',()=>{const s=ready();s.players.filter(p=>p.role==='villager'&&p.id!==12).forEach(p=>p.alive=false);transform(s,12);assert.equal(s.winner,'狼人陣營');assert.equal(s.step,'dawn');assert.equal(selectSeat(s,4),false);assert.equal(s.potions.poison,true);});
